networks:
  ralff-network:
    driver: bridge

services:
  backend:
    container_name: ralff-be
    build:
      context: ./ralff-be
    networks:
      - ralff-network
    ports:
      - "8080:8080"
    volumes:
      - ./learned-models:/usr/local/tomcat/learned-models
    environment:
      - OUTDIR_LEARNED_MODELS=learned-models

  frontend:
    container_name: ralff-fe
    build:
      context: ./ralff-fe
    networks:
      - ralff-network
    ports:
      - "3055:3055"
    environment:
      - VITE_RALFF_BE_WS=ws://localhost:8080/ralff-be/websocket